pipeline {
    agent {
        kubernetes {
            label 'charts-builder'
            defaultContainer 'tools'
            yaml """
apiVersion: v1
kind: Pod
spec:
  containers:
    - name: tools
      image: ubuntu:22.04
      command:
      - cat
      tty: true
      securityContext:
        privileged: true
      volumeMounts:
      - mountPath: "/usr/local/bin"
        name: bin-volume
      - mountPath: "/home/jenkins/agent"
        name: workspace-volume
      - mountPath: "/var/lib/docker"
        name: docker-volume
  volumes:
  - emptyDir: {}
    name: bin-volume
  - emptyDir:
      medium: ""
    name: workspace-volume
  - emptyDir: {}
    name: docker-volume
"""
        }
    }

    stages {
        stage('Clonar repositorio principal') {
            steps {
                script {
                    dir('repo-principal') {
                        git branch: 'develop', url: 'https://github.com/stemdo-labs/iac-ibmcloud-aitorcajas.git'
                    }
                }
            }
        }

        stage('Entorno') {
            steps {
                script {
                    def environment = load 'repo-principal/vars/environment.groovy'
                    environment.environment()
                }
            }
        }

        stage('CI') {
            steps {
                script {
                    def ci = load 'repo-principal/vars/ci.groovy'
                    ci.ci(env.ENVIRONMENT, env.DEVELOPMENT)
                }
            }
        }
    }
}