apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: acajas-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: 
    http:
      paths:
      - path: /development-acajas
        pathType: Prefix
        backend:
          service:
            name: frontend-development
            port:
              number: 80
      - path: /production-acajas
        pathType: Prefix
        backend:
          service:
            name: frontend-production
            port:
              number: 80
