apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: frontend-dev
  namespace: acajas
spec:
  path: /
  to:
    kind: Service
    name: frontend-development
  port:
    targetPort: 8090
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
    certificate: |
      -----BEGIN CERTIFICATE-----
      MIIEAzCCAuugAwIBAgIUU761VJDAYrOfX3z846RPlAd9VfIwDQYJKoZIhvcNAQEL
      BQAwgZAxCzAJBgNVBAYTAlNQMQ8wDQYDVQQIDAZUb2xlZG8xHTAbBgNVBAcMFFRh
      bGF2ZXJhIGRlIGxhIFJlaW5hMQ8wDQYDVQQKDAZTdGVtZG8xDzANBgNVBAsMBkRl
      dk9wczEOMAwGA1UEAwwFQWl0b3IxHzAdBgkqhkiG9w0BCQEWEGFjYWphc0BzdGVt
      ZG8uaW8wHhcNMjUwMTEwMTAwOTE3WhcNMjYwMTEwMTAwOTE3WjCBkDELMAkGA1UE
      BhMCU1AxDzANBgNVBAgMBlRvbGVkbzEdMBsGA1UEBwwUVGFsYXZlcmEgZGUgbGEg
      UmVpbmExDzANBgNVBAoMBlN0ZW1kbzEPMA0GA1UECwwGRGV2T3BzMQ4wDAYDVQQD
      DAVBaXRvcjEfMB0GCSqGSIb3DQEJARYQYWNhamFzQHN0ZW1kby5pbzCCASIwDQYJ
      KoZIhvcNAQEBBQADggEPADCCAQoCggEBAKKzk8YAhMc64F3QjGUiikgD9Z3HlQW3
      TuWHT/6gyW87DfNCqgUGZJ9Mi3GExtn0ZeWCoQ6ZziyvgRMhJFbWD30R39HCm2/k
      TnGECZXLctcypB3cRc+GjDDS2CuBs4B1lqTIWevEdBCCQFDK/6aL3x5J4yKGMaQs
      uyYK+WA68yZR1RyZ9ME8/hJplESKn7Leei4Wq7PfmsTLaVMF6yNLuWvijuqDFrW8
      WeQFHUm1l8KHYmEC/Y3BmpTTKOUZGC4jRnLr7o5zCvLjWvZCyYfJ23Vub57qfz6A
      AAE7D2NVbOamrSx/JzthhpDl4Wks0oJf1JekjxA29a/6XOklk67AnwECAwEAAaNT
      MFEwHQYDVR0OBBYEFMe8/yYa5BSvq+VEmU8HuIjQfV51MB8GA1UdIwQYMBaAFMe8
      /yYa5BSvq+VEmU8HuIjQfV51MA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQEL
      BQADggEBACx2XquBQemvAxMeuA/JAlLndSBxrTg2NshbPOm6qBRnZlNHGq2otJL9
      9xpiHs6lFCuzdh1Gvwax+RP6Xop3xoQIrmP7xolbgzQSSIX1D6oz10KAY57ssiCM
      iNziFl52CIOxHLj/V9ERCP1d3M4y2UUoPZiUA1eVQhNGI+jFv9oDzoYvU47khzIH
      A+6bq6NPqBJAknTZavZ8O5mA0ViuDE9ixuL7eDsZBHUndAcq3NeDG62rCtZvKC07
      xbetCN8bm4Vs7rhM1uUgNGHqWdAe50x/d0y8YPpXfiIJ0WhhXk/QavhBJ7WyHwJi
      7QLXB9AjKNK9R7U3BvI1BOBTw532a9s=
      -----END CERTIFICATE-----
    key: |
      -----BEGIN PRIVATE KEY-----
      MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCis5PGAITHOuBd
      0IxlIopIA/Wdx5UFt07lh0/+oMlvOw3zQqoFBmSfTItxhMbZ9GXlgqEOmc4sr4ET
      ISRW1g99Ed/Rwptv5E5xhAmVy3LXMqQd3EXPhoww0tgrgbOAdZakyFnrxHQQgkBQ
      yv+mi98eSeMihjGkLLsmCvlgOvMmUdUcmfTBPP4SaZREip+y3nouFquz35rEy2lT
      BesjS7lr4o7qgxa1vFnkBR1JtZfCh2JhAv2NwZqU0yjlGRguI0Zy6+6Ocwry41r2
      QsmHydt1bm+e6n8+gAABOw9jVWzmpq0sfyc7YYaQ5eFpLNKCX9SXpI8QNvWv+lzp
      JZOuwJ8BAgMBAAECggEBAIMIl3G2xzjhLQPBSuDEsZOQRMbejyE8YXkvwfgzLCe9
      6t1Iij9jx7QX5JH3OmMcltgBnY5xxn9slUp/vZGF8pFqzNRVo/O4boizqziN0p6H
      9W7rEPoyxUMo+9oGKjfB/CIYDXt5C3SkQgIPi1dpfLcbEKekZeRv9gWMfwzGTT9F
      DdS4iCE1RENAHmvJYAmZxREPjtb9CCmTbJwEqVuyKGGZW9vNrzLRp5UEIMHdgwzM
      1d1ljBcnm1iQN4IA8SYoujvz+BoW5etGEgqbkeVJoW9H07fPm7IH2g+8LPWk3r0I
      I8IWQJGi7UDF47FwbrISM96kfLAAdmeZ/Kf060uSOsECgYEAz0NbKfmEfgCVFRqk
      BhstsxqwRgCLuYQSABlACEAlWQ1gHJdgEnw/m8lVBkeJr8mZOqvfDnWOkDpPzFCl
      CqKBEmozScOTWwj2UZOjUqtIu7eixMGl1n+QkfBKwsarT41RhI41pf12UBGKINP8
      sGKb18xY0nmPpUHoGZieWgyHJHkCgYEAyPW9FoXKI2YNbioA7YkclxVlL2jCxlr4
      im2e4j2QvdqLtpETkYnWPy4fxvhTARcYLJ1pOhIiGdvirFTG/vcU06vWn2sK/W8l
      sg22OVd6u5RoRE7W8IznCeG+qdqKK07y6xPWVnpZqu7+1skYNhhKt6tdc/VyHCsd
      6rN9Udp13MkCgYEAghdF7ke2GJxm9rMdBtQiUAvNXnLTQKMb5UH0Bfm1N3sEu41r
      +M5R4odxPZrDWjnQWposTFgPHonrMlPf85fiKdvMy1zdbcNnT/a6CZaG9YQivxrI
      66Rv6poHYs/uEOWjp+7Wz5QSodkQeOB194Q9SyrxCVLRjambdA1uPxkj7gkCgYBB
      6hhzYr7CjZ6qG6ziPK7b/3CI9Fuuo/gRr5MFshvfqedZooxAmG1lm8Ngh+Lx4JlV
      SOxS18/Hm4/l5oi+6Fw0cZCcCYg5SFOc61JxzHe9PxhUD2gAzraZTyoynDPlsKeM
      45zSEJ+IqYt898ixNZaMV/D3L/KVuq69ZNIeHwG5wQKBgA3FXQa2NPesFPEm8SAS
      fMALCg51kGeS6jXawKMKQohj70UZw3bLbhSDWDCGOPSC9kWX+cdoYOOOodJGefnW
      Ig4n8p8tVsIlq0VdOdVY3NEKX8Vzhc5KsaIO4Fhbuhe8uxVYOXGg3UuBu4eaQ0DB
      lGDOqGngvX9gkyTetYg6LfWO
      -----END PRIVATE KEY-----
    caCertificate: |
      -----BEGIN CERTIFICATE-----
      MIIEAzCCAuugAwIBAgIUJ3W6WQ8MbqeLDQlKuiNL4Vn3+OwwDQYJKoZIhvcNAQEL
      BQAwgZAxCzAJBgNVBAYTAlNQMQ8wDQYDVQQIDAZUb2xlZG8xHTAbBgNVBAcMFFRh
      bGF2ZXJhIGRlIGxhIFJlaW5hMQ8wDQYDVQQKDAZTdGVtZG8xDzANBgNVBAsMBkRl
      dk9wczEOMAwGA1UEAwwFQWl0b3IxHzAdBgkqhkiG9w0BCQEWEGFjYWphc0BzdGVt
      ZG8uaW8wHhcNMjUwMTEwMTAxNzQ5WhcNMjYwMTEwMTAxNzQ5WjCBkDELMAkGA1UE
      BhMCU1AxDzANBgNVBAgMBlRvbGVkbzEdMBsGA1UEBwwUVGFsYXZlcmEgZGUgbGEg
      UmVpbmExDzANBgNVBAoMBlN0ZW1kbzEPMA0GA1UECwwGRGV2T3BzMQ4wDAYDVQQD
      DAVBaXRvcjEfMB0GCSqGSIb3DQEJARYQYWNhamFzQHN0ZW1kby5pbzCCASIwDQYJ
      KoZIhvcNAQEBBQADggEPADCCAQoCggEBANwT3tlQnksP/PLlgCXeJ3TjrPJmANPH
      r8Cfmltg126dip+dydM/CEaaIZqUiKNsTXsvV87UKVQNNf6O0DYYlmBnTTaRzrvk
      6qoPRU70uotEmizKyIg9O03cmdNaxF4IDwMhmWO24n4z9cgqySsEwNGM0BZjxI47
      6cwWFWdApD94xGGBeEApSWamz8yrQrdxCjUdnNOSTIp3WY5EyfWosK6DeFNKeCgO
      GNfSB3RwgnX+rjbR1BbXWlHPUx96rjwW4ZYjv1UXXVx9iZmRZ3nRsyt7Iuw0tHAK
      9XFGz9RT5V4vv8HwgAQ/XjoMtx5CqhI6xNGhZW1wNHjKhdpCZpJIs2sCAwEAAaNT
      MFEwHQYDVR0OBBYEFFGkufxixQIJSk/cm11EidPHZqvLMB8GA1UdIwQYMBaAFFGk
      ufxixQIJSk/cm11EidPHZqvLMA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQEL
      BQADggEBAMu9UqUCRLwtdNMM3B8cl4HkQSLO6otON+rg7IqpraFF6SnDc05GP4jV
      tiTXC+thLreRgh/07K3RjHlIWHUn4bl+dhidbDsDyyMVxLae7i8xqPZJBJteEkOI
      5WlN22b9giWnRQZdXWJwpQA0Z+FT7BZaxB4qx9gBTsj4oGFQTK53BLImjGru3z/+
      MCm9gYRCiVW/PW9mvREzSEMN2GnCtGA2+X9JN/cTr5oRl+MEYq9SMljTgfB0GE/O
      derwrKQNkwE4OWMYHHG7XrDoUKWSF59kIb09s4L5xGe2Ybm4E1TfWVJjccxR0k0k
      K02mR25ZdOhcVqse2Kd5YI13weeZ8zM=
      -----END CERTIFICATE-----