#Nombre del namespace donde se desplegará
namespace: acajas

#Número de replicas
replicas: 1

# Imagen
image: icr.io/acajas-cr/frontend-development:1.0.2

# Recursos
recursos:
  limites:
    memoria: "400Mi"
    cpu: "300m"
  requests:
    memoria: "200Mi"
    cpu: "100m"