name: Build

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extraer versión
        id: version
        run: |
          VERSION=$(jq -r '.version' package.json)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - uses: sonarsource/sonarqube-scan-action@v4
        with:
          args: >
            -Dsonar.projectVersion=${{ steps.version.outputs.VERSION }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        # continue-on-error: true

      - name: Extraer task id
        id: extract_task_id
        run: |
          cat .scannerwork/report-task.txt
          TASK_ID=$(cat .scannerwork/report-task.txt | grep -oP 'ceTaskId=\K.*')
          echo "TASK_ID=$TASK_ID" >> $GITHUB_OUTPUT

      - name: Generar reporte
        run: |
          curl -u ${{ secrets.SONAR_TOKEN }}: "${{ secrets.SONAR_HOST_URL }}/api/ce/task?id=${{ steps.extract_task_id.outputs.TASK_ID }}" > report.json
          cat report.json | jq . > sonar-report.json

      - name: Upload SonarQube report artifact
        uses: actions/upload-artifact@v3
        with:
          name: sonar-report
          path: sonar-report.json