name: Build

on:
  workflow_dispatch:

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extraer versión
        id: version
        run: |
          VERSION=$(jq -r '.version' package.json)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Extract sonar.projectKey
        id: project_key
        run: |
          KEY=$(grep -oP '^sonar.projectKey=\K.*' sonar-project.properties)
          echo "KEY=$KEY" >> $GITHUB_OUTPUT

      - name: SonarQube Analysis
        uses: stemdo-labs/S-SDLC_SonarQube/.github/workflows/sonarqube-analysis.yml@acajas-branch
        with:
          version: ${{ steps.version.outputs.VERSION }}
          project_key: ${{ steps.project_key.outputs.KEY }}
        secrets: inherit