name: CI-CD frontend
#
on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  environment:
    uses: stemdo-labs/final-project-exercise-aitorcajas/.github/workflows/environment.yml@main

  ci:
    needs: environment
    uses: stemdo-labs/final-project-exercise-aitorcajas/.github/workflows/ci.yml@main
    with:
      entorno: ${{ needs.environment.outputs.entorno }}
      desarrollo: ${{ needs.environment.outputs.desarrollo }}
    secrets: inherit

  cd:
    needs: [ci, environment]
    uses: stemdo-labs/final-project-exercise-aitorcajas/.github/workflows/cd.yml@main
    with:
      desarrollo: ${{ needs.environment.outputs.desarrollo }}
      entorno: ${{ needs.environment.outputs.entorno }}
    secrets: inherit