name: Buildear imagen del frontend

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: stemdo-labs/final-project-exercise-aitorcajas/.github/workflows/image-build.yml@main
    secrets:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
