name: Buildear imagen del frontend

on:
  workflow_dispatch:

jobs:
  build:
    uses: stemdo-labs/final-project-exercise-aitorcajas/.github/workflows/image-build.yml@main
    secrets:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      HARBOR_USER: ${{ secrets.HARBOR_USER }}
      HARBOR_PASS: ${{ secrets.HARBOR_PASS }}
